###
# Get All Todos
GET http://localhost:8080/todo

###
# Get one Todo
GET http://localhost:8080/todo/9d296425-22e8-4ad5-9e48-e5d6b788086


###
POST http://localhost:8080/todo HTTP/1.1
content-type: application/json

[
    {
        "name": "creando mi tarea"
    },
    {
        "name": "creando mi tarea"
    },
    {
        "name": "creando mi tarea"
    },
    {
        "name": "creando mi tarea"
    }
]